# Generated by Django 4.1.3 on 2022-12-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('reporter_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('NE', 'News'), ('SP', 'Sports'), ('PO', 'Politics'), ('BU', 'Business')], default='NE', max_length=2)),
                ('blog_content', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
